# Generated by Django 5.1.6 on 2025-03-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toc', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Élément du carousel',
                'verbose_name_plural': 'Éléments du carousel',
                'ordering': ['order'],
            },
        ),
    ]
