# Generated by Django 5.1.6 on 2025-03-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toc', '0003_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Nom descriptif du service', max_length=200, verbose_name='Titre du service')),
                ('description', models.TextField(help_text='Description détaillée du service', verbose_name='Description')),
                ('categorie', models.CharField(choices=[('sanitaire', 'Produits Sanitaires'), ('electricite', 'Électricité'), ('vitrerie', 'Vitre et Miroir'), ('suivi_chantier', 'Suivi de Chantier')], help_text='Catégorie à laquelle appartient le service', max_length=50, verbose_name='Catégorie')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, help_text='Prix du service (optionnel)', max_digits=10, null=True, verbose_name='Prix')),
                ('actif', models.BooleanField(default=True, help_text='Indique si le service est actuellement proposé', verbose_name='Service actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['titre'],
            },
        ),
    ]
