# Generated by Django 5.1.6 on 2025-03-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toc', '0004_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
